version: "3.8"
services:
  keycloak:
    build: keycloak
    ports:
      - "8180:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_FRONTEND_URL=http://localhost:8180/auth

  bips:
    build: bips-backend
    ports:
      - "8080:8080"
    #enable this port forward for remote debugging
    #      - "5005:5005"
    environment:
      - KEYCLOAK_URL=http://keycloak:8080/auth
    depends_on:
      - keycloak